-- MySQL Script generated by MySQL Workbench
-- Mon Feb  3 14:46:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema main_db_food_suggestor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema main_db_food_suggestor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `main_db_food_suggestor` DEFAULT CHARACTER SET utf8 ;
USE `main_db_food_suggestor` ;

-- -----------------------------------------------------
-- Table `main_db_food_suggestor`.`categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_db_food_suggestor`.`categorie` ;

CREATE TABLE IF NOT EXISTS `main_db_food_suggestor`.`categorie` (
  `ID` TINYINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_category` TINYINT(5) UNSIGNED NOT NULL,
  `related_category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_category_UNIQUE` (`ID_category` ASC) VISIBLE,
  UNIQUE INDEX `related_category_UNIQUE` (`related_category` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `main_db_food_suggestor`.`db_aliments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_db_food_suggestor`.`db_aliments` ;

CREATE TABLE IF NOT EXISTS `main_db_food_suggestor`.`db_aliments` (
  `ID` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `categorie` SMALLINT(5) NOT NULL,
  `nom_aliment` VARCHAR(50) NOT NULL,
  `magasin` VARCHAR(30) NOT NULL,
  `lien` VARCHAR(255) NOT NULL,
  `nutriscore` TINYTEXT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `main_db_food_suggestor`.`magasins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_db_food_suggestor`.`magasins` ;

CREATE TABLE IF NOT EXISTS `main_db_food_suggestor`.`magasins` (
  `ID` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_magasin` SMALLINT(5) UNSIGNED NOT NULL,
  `related_magasin` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_magasin_UNIQUE` (`ID_magasin` ASC) VISIBLE,
  UNIQUE INDEX `related_magasin_UNIQUE` (`related_magasin` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `main_db_food_suggestor`.`substitut`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_db_food_suggestor`.`substitut` ;

CREATE TABLE IF NOT EXISTS `main_db_food_suggestor`.`substitut` (
  `ID` TINYINT(5) UNSIGNED NOT NULL,
  `ID_produit_initial` TINYINT(5) UNSIGNED NOT NULL,
  `ID_produit_substitution` TINYINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_produit_base_UNIQUE` (`ID_produit_initial` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
